version: 2.1

orbs:
  windows: circleci/windows@2.4.0

commands:
  test-prep:
    parameters:
      version:
        default: current
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-<< parameters.version >>-deps-{{ arch }}-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - node-<< parameters.version >>-deps-{{ arch }}-v1-{{ checksum "package.json" }}-
            - node-<< parameters.version >>-deps-{{ arch }}-v1-
      - run:
          name: Install packages
          command: npm ci
      - save_cache:
          key: node-<< parameters.version >>-deps-{{ arch }}-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
              - ~/.npm

jobs:
  test-linux:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/node:<< parameters.version >>
    steps:
      - test-prep:
          version: << parameters.version >>
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Report to coveralls
          when: on_success
          command: npm run coverage
  test-macos:
    parameters:
      version:
        type: string
    macos:
      xcode: << parameters.version >>
    steps:
      - test-prep:
          version: << parameters.version >>
      - run:
          name: Run Tests
          command: npm test
  test-windows:
    executor:
      name: windows/default
    steps:
      - test-prep:
          version: default
      - run:
          name: Run Tests
          command: npm test
          shell: bash.exe

workflows:
  test:
    jobs:
      - test-linux:
          matrix:
            parameters:
              version:
                - lts
                - "16.18.1"
                - "14.21.1"
      # - test-macos:
      #     matrix:
      #       parameters:
      #         version:
      #         - "14" # Node 14
      - test-windows
