version: 2.1

orbs:
  windows: circleci/windows@2.4.0

commands:
  test:
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ arch }}-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - node-deps-{{ arch }}-v1-{{ checksum "package.json" }}-
            - node-deps-{{ arch }}-v1-
      - run:
          name: Install packages
          command: npm ci
      - save_cache:
          key: node-deps-{{ arch }}-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
              - ~/.npm
      - run:
          name: Run Tests
          command: npm test

jobs:
  test-linux:
    parameters:
      version:
        default: latest
        type: string
    docker:
      - image: cimg/node:<< parameters.version >>
    steps:
      - test
  test-macos:
    parameters:
      version:
        default: latest
        type: string
    macos:
      xcode: << parameters.version >>
    steps:
      - test
  test-windows:
    executor:
      name: windows/default
    steps:
      - test

workflows:
  test:
    jobs:
      - test-linux:
          matrix:
            parameters:
              version:
                - latest
                - lts
                - "12.22"
      - test-macos:
          matrix:
            parameters:
              version:
              - "11.2.1" # Node 12
              - "12.5.1" # Node 14
      - test-windows
