version: 2.1

orbs:
  node: circleci/node@4.6
  windows: circleci/windows@2.4.0

jobs:
  test:
    parameters:
      version:
        default: latest
        type: string
    executor:
      name: node/default
      tag: << parameters.version >>
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests
          command: npm test
  test-windows:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ arch }}-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - node-deps-{{ arch }}-v1-{{ checksum "package.json" }}-
            - node-deps-{{ arch }}-v1-
      - run:
          name: Install packages
          command: npm ci
      - save_cache:
          key: node-deps-{{ arch }}-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
              - ~/.npm
      - run:
          name: Run Tests
          command: npm test

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              # version: ["latest", "lts", "12.22"]
              version: ["12.22"]
      - test-windows
